name: Terraform Destroy Manual Workflow Trigger

on:
  workflow_dispatch:
  # push:
       inputs:
         environment:
         description: 'Environment to run tests against'
         # type: environment
         required: true
      # - main # Replace with the branch you want to trigger the workflow on

jobs:
  terraform:
    name: "Manual Trigger job"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-south-1'
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Destroy Terraform
      run: terraform destroy -auto-approve
